# Generated by Django 5.0.6 on 2024-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='blog', max_length=255),
            preserve_default=False,
        ),
    ]
